import os
import requests
from requests.auth import HTTPBasicAuth
from dotenv import load_dotenv
load_dotenv()

def _base_url() -> str:
    """
    Ensures we always use base like https://your-domain.atlassian.net
    """
    url = (os.getenv("JIRA_BASE_URL") or "").strip()
    if not url:
        raise ValueError("JIRA_BASE_URL is missing in .env")

    # Remove trailing slash if present
    url = url.rstrip("/")

    # If someone accidentally put /jira at end, remove it
    if url.endswith("/jira"):
        url = url[:-5]

    return url


def _auth() -> HTTPBasicAuth:
    email = (os.getenv("JIRA_EMAIL") or "").strip()
    token = (os.getenv("JIRA_API_TOKEN") or "").strip()
    if not email or not token:
        raise ValueError("JIRA_EMAIL or JIRA_API_TOKEN missing in .env")
    # Jira Cloud basic auth uses email + API token (password auth is deprecated)
    return HTTPBasicAuth(email, token)


# def test_jira_connection() -> dict:
#     """
#     Quick test: calls /rest/api/3/myself
#     If auth works, Jira returns user details.
#     """
#     url = f"{_base_url()}/rest/api/3/myself"
#     resp = requests.get(url, auth=_auth(), headers={"Accept": "application/json"}, timeout=30)
#     if resp.status_code >= 400:
#         raise ValueError(f"Jira connection failed {resp.status_code}: {resp.text}")
#     return resp.json()
def test_jira_connection() -> dict:
    """
    Full Jira diagnostic:
    1. Checks env variables
    2. Validates auth (/myself)
    3. Lists projects (/project/search)
    4. Prints EVERYTHING needed to debug
    """
    import json

    print("\n========== JIRA DEBUG START ==========\n")

    # 🔹 ENV DEBUG
    base_url = os.getenv("JIRA_BASE_URL")
    email = os.getenv("JIRA_EMAIL")
    token = os.getenv("JIRA_API_TOKEN")

    print("ENV CHECK:")
    print("JIRA_BASE_URL:", base_url)
    print("JIRA_EMAIL:", email)
    print("JIRA_API_TOKEN:", "SET" if token else "MISSING")

    if not base_url or not email or not token:
        raise ValueError("❌ Missing required env variables")

    base_url = base_url.rstrip("/")
    if base_url.endswith("/jira"):
        base_url = base_url[:-5]

    print("\nNormalized BASE URL:", base_url)

    auth = HTTPBasicAuth(email, token)
    headers = {"Accept": "application/json"}

    # 🔹 STEP 1: TEST AUTH
    print("\n--- Testing /myself ---")
    url_myself = f"{base_url}/rest/api/3/myself"
    resp = requests.get(url_myself, auth=auth, headers=headers, timeout=30)

    print("Status:", resp.status_code)
    print("Response:", resp.text[:500])

    if resp.status_code >= 400:
        raise ValueError(f"❌ Jira auth failed {resp.status_code}: {resp.text}")

    user_data = resp.json()
    print("\n✅ Auth successful:", user_data.get("emailAddress"))

    # 🔹 STEP 2: LIST PROJECTS
    print("\n--- Fetching Projects ---")
    url_projects = f"{base_url}/rest/api/3/project/search"
    resp_proj = requests.get(url_projects, auth=auth, headers=headers, timeout=30)

    print("Status:", resp_proj.status_code)
    print("Raw Response:", resp_proj.text[:1000])

    if resp_proj.status_code >= 400:
        raise ValueError(f"❌ Project fetch failed {resp_proj.status_code}: {resp_proj.text}")

    projects_data = resp_proj.json()

    print("\n📦 Projects Found:")
    project_keys = []

    for proj in projects_data.get("values", []):
        key = proj.get("key")
        name = proj.get("name")
        project_keys.append(key)
        print(f" - {key}: {name}")

    print("\n✅ Total Projects:", len(project_keys))

    print("\n========== JIRA DEBUG END ==========\n")

    return {
        "user": user_data,
        "projects": project_keys
    }


def _to_adf(text: str) -> dict:
    """
    Jira Cloud API v3 expects Atlassian Document Format (ADF) for description fields.
    """
    text = (text or "").strip()
    if not text:
        text = "Generated by PMO Agent"
    return {
        "type": "doc",
        "version": 1,
        "content": [
            {
                "type": "paragraph",
                "content": [{"type": "text", "text": text}]
            }
        ]
    }


def create_jira_issue(jira_payload: dict) -> dict:
    """
    Creates a Jira issue using /rest/api/3/issue.
    Uses jira_payload from your CR agent output.
    """
    project_key = jira_payload.get("project_key") or os.getenv("JIRA_PROJECT_KEY")
    issue_type = jira_payload.get("issue_type") or os.getenv("JIRA_ISSUE_TYPE") or "Task"

    summary = jira_payload.get("summary", "PMO Change Request")
    description_text = jira_payload.get("description", "")

    if not project_key:
        raise ValueError("JIRA_PROJECT_KEY missing (or jira_payload.project_key is empty)")

    body = {
        "fields": {
            "project": {"key": project_key},
            "issuetype": {"name": issue_type},
            "summary": summary,
            "description": _to_adf(description_text),
        }
    }

    # Optional fields if present
    if jira_payload.get("labels"):
        body["fields"]["labels"] = jira_payload["labels"]

    url = f"{_base_url()}/rest/api/3/issue"
    resp = requests.post(
        url,
        auth=_auth(),
        headers={"Accept": "application/json", "Content-Type": "application/json"},
        json=body,
        timeout=30
    )

    
    return resp.json()

test_jira_connection()
